In [7]:
#We can import packages in Python that contain specialized objects that are not available in the basic Python package.
#One example of these packages is NumPy.
import numpy as np
#It's convention to give numpy the name 'np' as an abbreviation.

In [8]:
#A great feature of numpy is its arrays. You can think of an array as a superpowered list. Let's create one.
#First create a list.
List = [23245, 27, 546, 215, -1234]

In [9]:
#Now lets use the list to create an array.
Array = np.array(List)

In [10]:
#Let's print the array to see what it looks like
print(Array)

[23245    27   546   215 -1234]


In [13]:
#We can also create an array from scratch like so.
Array2 = np.array([1, 2, 3, 4, 5])
print(Array2)

[1 2 3 4 5]


In [14]:
#Keep in mind that arrays are only meant to be used with integer/float variables.
#Arrays have built in functions that makes finding basic summary statistics very easy. For example...
print(Array2.mean())
print(Array2.max())
print(Array2.min())

3.0
5
1


In [15]:
#We can also slice arrays like we would slice lists. Like so...
Array2[2:4]

array([3, 4])